---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: unified-logging
  labels:
    app: unified-logging
spec:
  replicas: 10
  selector:
    matchLabels:
      app: unified-logging
  template:
    metadata:
      labels:
        app: unified-logging
    spec:
      containers:
      - name: unified-logging
        image: us.gcr.io/${PROJECT_ID}/logger-generator:latest
        args:
        - "1"
        - "5"
